repos:
  - repo: local
    hooks:
      - id: conventional-commit
        name: Check conventional commit messages
        language: system
        entry: python ./hooks/conventional-message.py
        stages: [commit-msg]
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args:
          - --line-length=10